### ISSUE TITLE
candidate.toLowerCase is not a function

### ISSUE THREAD

**Issue by christianherweg0807** [premisedata/dynamic-data-form-extension#23]
Hey. I followed the steps in the README of you dynamic-pick-extension.
I created a small template in the Template Editor:
`---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: open-pr-with-business-catalog-entry-product
spec:
  parameters:
    - title: What is your service about?
      properties:
        name:
          title: "Name"
          type: string
          ui:field: DynamicPickExtension
          ui:autofocus: true
          ui:options:
            external_data: https://dummyjson.com/products/categories
`
When clicking in the dropdown field I got an :

TypeError
candidate.toLowerCase is not a function

<img width="1247" alt="image" src="https://github.com/premisedata/dynamic-data-form-extension/assets/39617537/fa550545-5e4d-4ad9-93f1-3476440d6174">
<img width="1422" alt="image" src="https://github.com/premisedata/dynamic-data-form-extension/assets/39617537/b041c302-fd11-450e-ada0-1e48d3bebfb9">

Any clue what I´ve missed?

**Comment by christianherweg0807** [comment]
My goal is to select GitHub repositorys per dropdown. I think I´ve to use your Backend Plugin for this, right?
Is your Plugin already migrated to the new Backend System?
In you Readme you have an example with :

form_data: github/teams

You you provide example code for this?

**Comment by nia-potato** [comment]
@nthings  hi thanks for the plugin, i am also getting the same error, is there anything we are missing in the setup?

**Comment by siarheirdn** [comment]
same issue :( example is wrong
https://www.npmjs.com/package/@premise/plugin-dynamic-pick-extension?activeTab=readme
```
parameters:
    - category:
        title: Category
        type: string
        ui:field: DynamicPickExtension
        ui:options:
            # IMPORTANT: The endpoint needs to return a JSON array of strings.
            external_data: https://dummyjson.com/products/categories
```
restApi https://dummyjson.com/products/categories returns list of objects instead of strings.
not a bug?
